import Link from "next/link";
import type { Metadata } from "next";
import { LegalSection as Section } from "@/components/LegalSection";

export const metadata: Metadata = {
  title: "Terms of Service — Plan My Workout",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white dark:bg-zinc-950 px-4 py-12">
      <div className="max-w-2xl mx-auto space-y-8 text-zinc-700 dark:text-zinc-300">

        <div>
          <Link href="/" className="text-xs text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-400 transition">← Home</Link>
          <h1 className="text-2xl font-bold text-zinc-900 dark:text-white mt-4">Terms of Service</h1>
          <p className="text-xs text-zinc-500 mt-1">Effective date: 10 March 2026</p>
        </div>

        <Section title="1. Acceptance">
          <p>By using Plan My Workout, you agree to these Terms. If you do not agree, do not use the app.</p>
        </Section>

        <Section title="2. What the app does">
          <p>Plan My Workout scans YouTube channels you add, classifies workout videos using AI, and generates a personalised weekly workout plan. You can optionally publish this plan to a YouTube playlist in your account.</p>
        </Section>

        <Section title="3. Health disclaimer">
          <p>The workout plans generated by this app are created automatically by AI based on video metadata. They are not created by certified fitness professionals. This app does not provide medical or fitness advice.</p>
          <p><strong className="text-zinc-800 dark:text-zinc-200">Consult a qualified healthcare or fitness professional before starting any exercise programme, particularly if you have any medical conditions or injuries.</strong> Use the generated plans at your own risk.</p>
        </Section>

        <Section title="4. AI-generated content">
          <p>Plans are generated automatically by AI and may not always be appropriate for your fitness level, goals, or health status. We make no guarantee about the accuracy, suitability, or completeness of generated plans.</p>
        </Section>

        <Section title="5. YouTube content">
          <p>This app surfaces videos from YouTube channels you choose. We do not host, own, or control any video content. All video content remains subject to the{" "}
            <a href="https://www.youtube.com/t/terms" target="_blank" rel="noopener noreferrer" className="text-zinc-600 dark:text-zinc-400 underline hover:text-zinc-900 dark:hover:text-white">YouTube Terms of Service</a>{" "}
            and the rights of the original creators. This app is not affiliated with YouTube, Google, or any featured channel creators.
          </p>
        </Section>

        <Section title="6. Your account">
          <p>You are responsible for maintaining the security of your Google account. You must not use the app to violate YouTube&apos;s Terms of Service or any applicable law.</p>
          <p>We reserve the right to suspend or delete accounts that misuse the service.</p>
        </Section>

        <Section title="7. Acceptable use">
          <p>You may not:</p>
          <ul>
            <li>Use the app to scrape or harvest data at scale</li>
            <li>Attempt to reverse-engineer, disrupt, or abuse the service</li>
            <li>Use the app in any way that violates applicable laws</li>
          </ul>
        </Section>

        <Section title="8. Disclaimer of warranties">
          <p>The app is provided &quot;as is&quot; without warranty of any kind. We do not guarantee uptime, accuracy of plans, or fitness of the service for any particular purpose.</p>
        </Section>

        <Section title="9. Limitation of liability">
          <p>To the fullest extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the app, including any injury resulting from following a generated workout plan.</p>
        </Section>

        <Section title="10. Changes to the service">
          <p>We may modify or discontinue the service at any time without notice.</p>
        </Section>

        <Section title="11. Changes to these terms">
          <p>We may update these Terms and will revise the effective date. Continued use after changes constitutes acceptance.</p>
        </Section>

        <Section title="12. Contact">
          <p>Questions? Email us at <a href="mailto:harshitspeaks@gmail.com" className="text-zinc-600 dark:text-zinc-400 underline hover:text-zinc-900 dark:hover:text-white">harshitspeaks@gmail.com</a>.</p>
        </Section>

      </div>
    </main>
  );
}

